apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sentiment-api-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - host: example.local
      http:
        paths:
          - path: /actuator(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: sentiment-api-service
                port:
                  number: 8080
          - path: /api/sentiment(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: sentiment-api-service
                port:
                  number: 8080